fortify-sast-scancentral:
image: fortifydocker/fortify-ci-tools:latest
script:
  	  CLIENT_KEY: ${{ secrets.CLIENT_KEY }}  
          SSC_URL: ${{ secrets.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SCANCENTRAL_BUILD_OPTS: ${{ secrets.SCANCENTRAL_BUILD_OPTS }}
	  POOL: ${{ secrets.POOL }}
	  SSC_APP: ${{ secrets.SSC_APP }}
          SSC_PV: ${{ secrets.SSC_PV }}
	  CI_TOKEN_SC: ${{ secrets.CI_TOKEN_SC }}
    - touch /opt/Fortify/ScanCentral/Core/config/client.properties
    - echo "client_auth_token=secrets.CLIENT_KEY" > /opt/Fortify/ScanCentral/Core/config/client.properties
    - 'scancentral -sscurl secrets.SSC_URL -ssctoken secrets.SSC_TOKEN start secrets.SCANCENTRAL_BUILD_OPTS -pool secrets.POOL -upload -application secrets.SSC_APP -version secrets.SSC_PV -uptoken secrets.CI_TOKEN_SC' 
  
  allow_failure: true
