fortify-sast-scancentral:
image: fortifydocker/fortify-ci-tools:latest

  # Update/override variables based on the ScanCentral Client documentation for your project's included tech stack(s). Helpful hints:
  #   ScanCentral Client will download dependencies for maven (-bt mvn) and gradle (-bt gradle).
  #   The current fortify-ci-tools image is Linux only at this time. Msbuild integration is not currently supported.
  #   ScanCentral has additional options that should be set for PHP and Python projects.
  #   For other build tools (-bt none), add your build commands to download necessary dependencies.
  #   ScanCentral documentation is located at https://www.microfocus.com/documentation/fortify-software-security-center/ 
  script:
  	  CLIENT_KEY: ${{ secrets.CLIENT_KEY }}  
          SSC_URL: ${{ secrets.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SCANCENTRAL_BUILD_OPTS: ${{ secrets.SCANCENTRAL_BUILD_OPTS }}
	  POOL: ${{ secrets.POOL }}
	  SSC_APP: ${{ secrets.SSC_APP }}
          SSC_PV: ${{ secrets.SSC_PV }}
	  CI_TOKEN_SC: ${{ secrets.CI_TOKEN_SC }}
    - touch /opt/Fortify/ScanCentral/Core/config/client.properties
    - echo "client_auth_token=secrets.CLIENT_KEY" > /opt/Fortify/ScanCentral/Core/config/client.properties
    - 'scancentral -sscurl secrets.SSC_URL -ssctoken secrets.SSC_TOKEN start secrets.SCANCENTRAL_BUILD_OPTS -pool secrets.POOL -upload -application secrets.SSC_APP -version secrets.SSC_PV -uptoken secrets.CI_TOKEN_SC' 
  
  allow_failure: true
